<?php
/**
 * Web installer – runs once from the browser (no terminal needed).
 * After a successful install it locks itself; delete this file afterwards.
 */
define('ROOT', __DIR__);
define('APP', ROOT . '/app');
define('APP_VERSION', 'install');

header('Content-Type: text/html; charset=utf-8');
header('X-Robots-Tag: noindex');

$installed = is_file(APP . '/config.php');

function h($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

$checks = [
    ['PHP نسخه ۷.۴ یا بالاتر', version_compare(PHP_VERSION, '7.4.0', '>='), PHP_VERSION],
    ['افزونه PDO MySQL', extension_loaded('pdo_mysql'), ''],
    ['افزونه mbstring', extension_loaded('mbstring'), ''],
    ['افزونه JSON', function_exists('json_encode'), ''],
    ['افزونه cURL (برای پیامک و درگاه)', function_exists('curl_init'), function_exists('curl_init') ? '' : 'در نبود cURL از روش جایگزین استفاده می‌شود'],
    ['پوشه app قابل نوشتن', is_writable(APP), ''],
    ['پوشه storage قابل نوشتن', is_writable(ROOT . '/storage'), ''],
    ['پوشه assets/cache قابل نوشتن', is_writable(ROOT . '/assets/cache'), ''],
    ['پوشه uploads قابل نوشتن', is_writable(ROOT . '/uploads'), ''],
];
$ok = true;
foreach ($checks as $c) if (!$c[1] && strpos($c[0], 'cURL') === false) $ok = false;

$https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');
$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
$dir = rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'])), '/');
$baseGuess = ($https ? 'https' : 'http') . '://' . $host . $dir;

$error = '';
$done = false;

if (!$installed && $_SERVER['REQUEST_METHOD'] === 'POST' && $ok) {
    $db = [
        'host' => trim($_POST['db_host']) ?: 'localhost',
        'port' => trim($_POST['db_port']),
        'name' => trim($_POST['db_name']),
        'user' => trim($_POST['db_user']),
        'pass' => (string)$_POST['db_pass'],
    ];
    $adminUser = preg_replace('/[^a-zA-Z0-9_.-]/', '', $_POST['admin_user']);
    $adminPass = (string)$_POST['admin_pass'];
    $baseUrl = rtrim(trim($_POST['base_url']), '/');
    if ($adminUser === '' || strlen($adminPass) < 8) {
        $error = 'نام کاربری مدیر (لاتین) و رمز حداقل ۸ کاراکتری لازم است.';
    } elseif (!preg_match('#^https?://#', $baseUrl)) {
        $error = 'آدرس سایت باید با http:// یا https:// شروع شود.';
    } else {
        try {
            $dsn = 'mysql:host=' . $db['host'] . ($db['port'] ? ';port=' . $db['port'] : '') . ';dbname=' . $db['name'] . ';charset=utf8mb4';
            $pdo = new PDO($dsn, $db['user'], $db['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $exists = $pdo->query("SHOW TABLES LIKE 'seats'")->fetchColumn();
            if ($exists) throw new Exception('جداول برنامه از قبل در این دیتابیس وجود دارند. یک دیتابیس خالی انتخاب کنید.');
            $sql = file_get_contents(ROOT . '/database/schema.sql');
            foreach (preg_split('/;\s*\n/', $sql) as $stmt) {
                $stmt = trim(preg_replace('/^--.*$/m', '', $stmt));
                if ($stmt !== '') $pdo->exec($stmt);
            }
            $config = [
                'db' => $db,
                'base_url' => $baseUrl,
                'pretty_urls' => isset($_POST['pretty']) && $_POST['pretty'] === '1',
                'app_key' => bin2hex(random_bytes(32)),
                'debug' => false,
            ];
            foreach (['storage/cache', 'storage/logs', 'storage/sessions'] as $d) {
                if (!is_dir(ROOT . '/' . $d)) @mkdir(ROOT . '/' . $d, 0755, true);
            }
            // boot the app with the new config to seed data
            $GLOBALS['config'] = $config;
            date_default_timezone_set('Asia/Tehran');
            require APP . '/lib/helpers.php';
            require APP . '/lib/db.php';
            require APP . '/lib/jdate.php';
            require APP . '/lib/seed.php';
            db_tx(function () use ($adminUser, $adminPass) {
                seed_all();
                db_insert('admins', ['username' => $adminUser, 'password_hash' => password_hash($adminPass, PASSWORD_DEFAULT), 'name' => 'مدیر سیستم', 'role' => 'admin', 'is_active' => 1, 'created_at' => now()]);
            });
            if (@file_put_contents(APP . '/config.php', "<?php\n// Generated by installer " . date('Y-m-d H:i') . "\nreturn " . var_export($config, true) . ";\n") === false) {
                throw new Exception('نوشتن فایل app/config.php ممکن نشد. دسترسی پوشه app را بررسی کنید.');
            }
            @unlink(ROOT . '/storage/cache/settings.php');
            $done = true;
            $installed = true;
        } catch (Throwable $e) {
            $error = $e->getMessage();
        }
    }
}
?>
<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>نصب سامانه همایش</title>
<link rel="stylesheet" href="assets/css/app.css">
</head>
<body>
<main><div class="container" style="max-width:640px">
  <h1>نصب سامانه رزرو همایش</h1>
  <?php if ($done): ?>
    <div class="alert ok">نصب با موفقیت انجام شد.</div>
    <div class="card">
      <p><b>مهم:</b> برای امنیت، فایل <code>install.php</code> را از روی هاست حذف کنید.</p>
      <p>گام‌های بعدی در پنل مدیریت:</p>
      <ol>
        <li>تنظیمات ← پیامک: کلید API ملی پیامک و کد الگوها</li>
        <li>تنظیمات ← درگاه: مرچنت زرین‌پال یا زیبال</li>
        <li>سانس‌ها ← تاریخ، ساعت و قیمت‌ها را بازبینی کنید</li>
        <li>کاربران پنل ← برای نیروهای پذیرش حساب «کنترل ورود» بسازید</li>
      </ol>
      <div class="row"><a class="btn" href="<?= h($dir) ?>/<?= !empty($config['pretty_urls']) ? 'admin' : 'index.php?r=/admin' ?>">ورود به پنل مدیریت</a>
      <a class="btn ghost" href="<?= h($dir) ?>/">مشاهده سایت</a></div>
    </div>
  <?php elseif ($installed): ?>
    <div class="alert info">سامانه قبلاً نصب شده است. برای نصب مجدد، فایل app/config.php را حذف کنید. فایل install.php را پاک کنید.</div>
  <?php else: ?>
    <div class="card">
      <h3>بررسی پیش‌نیازها</h3>
      <table class="t">
        <?php foreach ($checks as $c): ?>
        <tr><td><?= h($c[0]) ?></td><td><?= $c[1] ? '<span class="badge ok">✔</span>' : '<span class="badge bad">✖</span>' ?> <span class="small muted"><?= h($c[2]) ?></span></td></tr>
        <?php endforeach ?>
      </table>
      <?php if (!$ok): ?><div class="alert err mt">ابتدا موارد قرمز را رفع کنید (معمولاً دسترسی پوشه‌ها را از فایل‌منیجر هاست روی 755 بگذارید).</div><?php endif ?>
    </div>
    <?php if ($error): ?><div class="alert err"><?= h($error) ?></div><?php endif ?>
    <form method="post" class="card">
      <h3>اطلاعات دیتابیس MySQL</h3>
      <p class="small muted">از بخش MySQL Databases در cPanel / DirectAdmin یک دیتابیس و کاربر بسازید و کاربر را با همه دسترسی‌ها به دیتابیس متصل کنید.</p>
      <div class="grid g2">
        <div class="field"><label>نام دیتابیس</label><input type="text" name="db_name" class="input-ltr" required value="<?= h(isset($_POST['db_name']) ? $_POST['db_name'] : '') ?>"></div>
        <div class="field"><label>نام کاربری دیتابیس</label><input type="text" name="db_user" class="input-ltr" required value="<?= h(isset($_POST['db_user']) ? $_POST['db_user'] : '') ?>"></div>
        <div class="field"><label>رمز دیتابیس</label><input type="password" name="db_pass" class="input-ltr"></div>
        <div class="field"><label>هاست دیتابیس</label><input type="text" name="db_host" class="input-ltr" value="<?= h(isset($_POST['db_host']) ? $_POST['db_host'] : 'localhost') ?>"></div>
        <div class="field"><label>پورت (اختیاری)</label><input type="text" name="db_port" class="input-ltr" value="<?= h(isset($_POST['db_port']) ? $_POST['db_port'] : '') ?>"></div>
      </div>
      <h3 class="mt">سایت و مدیر</h3>
      <div class="field"><label>آدرس سایت</label><input type="text" name="base_url" class="input-ltr" value="<?= h(isset($_POST['base_url']) ? $_POST['base_url'] : $baseGuess) ?>">
        <div class="help">حتماً با https باشد (برای درگاه پرداخت و دوربین اسکنر لازم است).</div></div>
      <div class="grid g2">
        <div class="field"><label>نام کاربری مدیر</label><input type="text" name="admin_user" class="input-ltr" required value="admin"></div>
        <div class="field"><label>رمز مدیر (حداقل ۸)</label><input type="password" name="admin_pass" class="input-ltr" required></div>
      </div>
      <input type="hidden" name="pretty" id="pretty" value="0">
      <p class="small muted" id="rw">در حال بررسی پشتیبانی از آدرس‌های تمیز…</p>
      <button class="btn lg block" type="submit" <?= $ok ? '' : 'disabled' ?>>نصب</button>
    </form>
    <script>
      fetch('__rewrite_test', {cache: 'no-store'}).then(function (r) { return r.ok ? r.text() : ''; }).then(function (t) {
        var ok = t.trim() === 'ok';
        document.getElementById('pretty').value = ok ? '1' : '0';
        document.getElementById('rw').textContent = ok ? '✔ آدرس‌های تمیز (mod_rewrite) فعال است.' : 'آدرس‌های تمیز در دسترس نیست؛ از آدرس‌های index.php?r= استفاده می‌شود (مشکلی ایجاد نمی‌کند).';
      }).catch(function () {});
    </script>
  <?php endif ?>
</div></main>
</body>
</html>
